# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_server_pb2 as chat__server__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientModuleStub(object):
    """Serviço para comunicação Cliente -> Servidor
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessageToServer = channel.unary_unary(
                '/chat_server.ClientModule/SendMessageToServer',
                request_serializer=chat__server__pb2.TextMessage.SerializeToString,
                response_deserializer=chat__server__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.SubscribeToServerEvents = channel.unary_stream(
                '/chat_server.ClientModule/SubscribeToServerEvents',
                request_serializer=chat__server__pb2.Empty.SerializeToString,
                response_deserializer=chat__server__pb2.TextMessage.FromString,
                _registered_method=True)
        self.GetLeader = channel.unary_unary(
                '/chat_server.ClientModule/GetLeader',
                request_serializer=chat__server__pb2.Empty.SerializeToString,
                response_deserializer=chat__server__pb2.LeaderInfo.FromString,
                _registered_method=True)


class ClientModuleServicer(object):
    """Serviço para comunicação Cliente -> Servidor
    """

    def SendMessageToServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeToServerEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLeader(self, request, context):
        """Cliente pergunta quem é o líder atual
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessageToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessageToServer,
                    request_deserializer=chat__server__pb2.TextMessage.FromString,
                    response_serializer=chat__server__pb2.StatusResponse.SerializeToString,
            ),
            'SubscribeToServerEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeToServerEvents,
                    request_deserializer=chat__server__pb2.Empty.FromString,
                    response_serializer=chat__server__pb2.TextMessage.SerializeToString,
            ),
            'GetLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLeader,
                    request_deserializer=chat__server__pb2.Empty.FromString,
                    response_serializer=chat__server__pb2.LeaderInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_server.ClientModule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_server.ClientModule', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientModule(object):
    """Serviço para comunicação Cliente -> Servidor
    """

    @staticmethod
    def SendMessageToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_server.ClientModule/SendMessageToServer',
            chat__server__pb2.TextMessage.SerializeToString,
            chat__server__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeToServerEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat_server.ClientModule/SubscribeToServerEvents',
            chat__server__pb2.Empty.SerializeToString,
            chat__server__pb2.TextMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_server.ClientModule/GetLeader',
            chat__server__pb2.Empty.SerializeToString,
            chat__server__pb2.LeaderInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServerModuleStub(object):
    """Serviço para broadcast de mensagens
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushMessageToClients = channel.unary_unary(
                '/chat_server.ServerModule/PushMessageToClients',
                request_serializer=chat__server__pb2.TextMessage.SerializeToString,
                response_deserializer=chat__server__pb2.StatusResponse.FromString,
                _registered_method=True)


class ServerModuleServicer(object):
    """Serviço para broadcast de mensagens
    """

    def PushMessageToClients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushMessageToClients': grpc.unary_unary_rpc_method_handler(
                    servicer.PushMessageToClients,
                    request_deserializer=chat__server__pb2.TextMessage.FromString,
                    response_serializer=chat__server__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_server.ServerModule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_server.ServerModule', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServerModule(object):
    """Serviço para broadcast de mensagens
    """

    @staticmethod
    def PushMessageToClients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_server.ServerModule/PushMessageToClients',
            chat__server__pb2.TextMessage.SerializeToString,
            chat__server__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ElectionModuleStub(object):
    """Serviço para Algoritmo de Eleição (Bully Algorithm)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Heartbeat = channel.unary_unary(
                '/chat_server.ElectionModule/Heartbeat',
                request_serializer=chat__server__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=chat__server__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Election = channel.unary_unary(
                '/chat_server.ElectionModule/Election',
                request_serializer=chat__server__pb2.ElectionRequest.SerializeToString,
                response_deserializer=chat__server__pb2.ElectionResponse.FromString,
                _registered_method=True)
        self.Coordinator = channel.unary_unary(
                '/chat_server.ElectionModule/Coordinator',
                request_serializer=chat__server__pb2.CoordinatorRequest.SerializeToString,
                response_deserializer=chat__server__pb2.CoordinatorResponse.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/chat_server.ElectionModule/SyncState',
                request_serializer=chat__server__pb2.SyncRequest.SerializeToString,
                response_deserializer=chat__server__pb2.SyncResponse.FromString,
                _registered_method=True)


class ElectionModuleServicer(object):
    """Serviço para Algoritmo de Eleição (Bully Algorithm)
    """

    def Heartbeat(self, request, context):
        """Heartbeat para detectar falhas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Election(self, request, context):
        """Mensagem ELECTION - um servidor inicia eleição
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Coordinator(self, request, context):
        """Mensagem COORDINATOR - anuncia o novo líder
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Sincronizar estado (mensagens) com o líder
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ElectionModuleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=chat__server__pb2.HeartbeatRequest.FromString,
                    response_serializer=chat__server__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Election': grpc.unary_unary_rpc_method_handler(
                    servicer.Election,
                    request_deserializer=chat__server__pb2.ElectionRequest.FromString,
                    response_serializer=chat__server__pb2.ElectionResponse.SerializeToString,
            ),
            'Coordinator': grpc.unary_unary_rpc_method_handler(
                    servicer.Coordinator,
                    request_deserializer=chat__server__pb2.CoordinatorRequest.FromString,
                    response_serializer=chat__server__pb2.CoordinatorResponse.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=chat__server__pb2.SyncRequest.FromString,
                    response_serializer=chat__server__pb2.SyncResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_server.ElectionModule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat_server.ElectionModule', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ElectionModule(object):
    """Serviço para Algoritmo de Eleição (Bully Algorithm)
    """

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_server.ElectionModule/Heartbeat',
            chat__server__pb2.HeartbeatRequest.SerializeToString,
            chat__server__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Election(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_server.ElectionModule/Election',
            chat__server__pb2.ElectionRequest.SerializeToString,
            chat__server__pb2.ElectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Coordinator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_server.ElectionModule/Coordinator',
            chat__server__pb2.CoordinatorRequest.SerializeToString,
            chat__server__pb2.CoordinatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat_server.ElectionModule/SyncState',
            chat__server__pb2.SyncRequest.SerializeToString,
            chat__server__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
